/*
 * Captive Portal — Embedded Configuration Web Page
 *
 * Mobile-friendly HTML form for device setup.
 * No external resources — everything is self-contained.
 *
 * Adapted from hey_livekit config_page.h — rebranded for general use.
 */

#pragma once

static const char PORTAL_PAGE_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>LiveKit ESP32 Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,system-ui,sans-serif;background:#0f172a;color:#e2e8f0;padding:16px;min-height:100vh}"
"h1{font-size:1.5rem;text-align:center;margin:16px 0;color:#7dd3fc}"
".subtitle{text-align:center;color:#94a3b8;margin-bottom:24px;font-size:0.9rem}"
"form{max-width:480px;margin:0 auto}"
".section{background:#1e293b;border-radius:12px;padding:16px;margin-bottom:16px}"
".section h2{font-size:1rem;color:#7dd3fc;margin-bottom:12px;border-bottom:1px solid #334155;padding-bottom:8px}"
"label{display:block;font-size:0.85rem;color:#94a3b8;margin:10px 0 4px}"
"input[type=text],input[type=password],input[type=url]{width:100%;padding:10px 12px;border:1px solid #334155;border-radius:8px;"
"background:#0f172a;color:#e2e8f0;font-size:1rem;outline:none;transition:border 0.2s}"
"input:focus{border-color:#38bdf8}"
"input::placeholder{color:#475569}"
".required::after{content:' *';color:#f87171}"
".btn{width:100%;padding:14px;border:none;border-radius:10px;font-size:1.1rem;font-weight:600;cursor:pointer;"
"margin-top:8px;transition:background 0.2s}"
".btn-primary{background:#0284c7;color:white}"
".btn-primary:hover{background:#0369a1}"
".btn-primary:active{background:#075985}"
".btn-danger{background:#991b1b;color:white;font-size:0.9rem;padding:10px;margin-top:24px}"
".btn-danger:hover{background:#7f1d1d}"
".status{max-width:480px;margin:16px auto;background:#1e293b;border-radius:12px;padding:16px;font-size:0.85rem}"
".status h2{font-size:1rem;color:#7dd3fc;margin-bottom:8px}"
".status-row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid #1e293b}"
".status-key{color:#94a3b8}.status-val{color:#e2e8f0}"
".msg{text-align:center;padding:12px;border-radius:8px;margin:12px 0;font-size:0.9rem;display:none}"
".msg-ok{background:#064e3b;color:#6ee7b7;display:block}"
".msg-err{background:#7f1d1d;color:#fca5a5;display:block}"
".toggle-pass{color:#38bdf8;font-size:0.8rem;cursor:pointer;float:right;margin-top:-18px}"
"</style>"
"</head>"
"<body>"
"<h1>LiveKit ESP32 Setup</h1>"
"<p class=\"subtitle\">Device Configuration</p>"
"<div id=\"msg\" class=\"msg\"></div>"
"<form id=\"cfg\" method=\"POST\" action=\"/config\">"

"<div class=\"section\">"
"<h2>WiFi Network</h2>"
"<label class=\"required\">SSID</label>"
"<input type=\"text\" name=\"wifi_ssid\" id=\"wifi_ssid\" placeholder=\"Your WiFi network\" required>"
"<label class=\"required\">Password</label>"
"<input type=\"password\" name=\"wifi_pass\" id=\"wifi_pass\" placeholder=\"WiFi password\" required>"
"<span class=\"toggle-pass\" onclick=\"toggleVis('wifi_pass',this)\">show</span>"
"</div>"

"<div class=\"section\">"
"<h2>LiveKit Server</h2>"
"<label>Server URL</label>"
"<input type=\"url\" name=\"lk_url\" id=\"lk_url\" placeholder=\"wss://your-server.livekit.cloud\">"
"<label>API Key</label>"
"<input type=\"text\" name=\"lk_api_key\" id=\"lk_api_key\" placeholder=\"APIxxxxxxx\">"
"<label>API Secret</label>"
"<input type=\"password\" name=\"lk_api_secret\" id=\"lk_api_secret\" placeholder=\"Secret key\">"
"<span class=\"toggle-pass\" onclick=\"toggleVis('lk_api_secret',this)\">show</span>"
"<label>Room Name</label>"
"<input type=\"text\" name=\"lk_room\" id=\"lk_room\" placeholder=\"my-room\">"
"</div>"

"<div class=\"section\">"
"<h2>Device Identity</h2>"
"<label>Device Name</label>"
"<input type=\"text\" name=\"device_id\" id=\"device_id\" placeholder=\"kitchen-speaker\">"
"</div>"

"<button type=\"submit\" class=\"btn btn-primary\">Save &amp; Reboot</button>"
"<button type=\"button\" class=\"btn btn-danger\" onclick=\"factoryReset()\">Factory Reset</button>"
"</form>"

"<div class=\"status\" id=\"status\"></div>"

"<script>"
"function toggleVis(id,el){"
"var i=document.getElementById(id);"
"if(i.type==='password'){i.type='text';el.textContent='hide'}"
"else{i.type='password';el.textContent='show'}"
"}"

"function showMsg(txt,ok){"
"var m=document.getElementById('msg');"
"m.textContent=txt;"
"m.className='msg '+(ok?'msg-ok':'msg-err');"
"}"

"document.getElementById('cfg').onsubmit=function(e){"
"e.preventDefault();"
"var fd=new FormData(this);"
"var obj={};"
"fd.forEach(function(v,k){obj[k]=v});"
"fetch('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)})"
".then(function(r){return r.json()})"
".then(function(d){"
"if(d.ok){showMsg('Saved! Rebooting in 3 seconds...',true);setTimeout(function(){},3000)}"
"else{showMsg('Error: '+(d.error||'unknown'),false)}"
"})"
".catch(function(e){showMsg('Network error: '+e,false)});"
"};"

"function factoryReset(){"
"if(!confirm('Erase ALL settings and reboot?'))return;"
"fetch('/reset',{method:'POST'})"
".then(function(r){return r.json()})"
".then(function(d){showMsg('Factory reset! Rebooting...',true)})"
".catch(function(e){showMsg('Error: '+e,false)});"
"}"

/* Load current config values */
"fetch('/status')"
".then(function(r){return r.json()})"
".then(function(d){"
"if(d.wifi_ssid)document.getElementById('wifi_ssid').value=d.wifi_ssid;"
"if(d.wifi_pass)document.getElementById('wifi_pass').value=d.wifi_pass;"
"if(d.lk_url)document.getElementById('lk_url').value=d.lk_url;"
"if(d.lk_api_key)document.getElementById('lk_api_key').value=d.lk_api_key;"
"if(d.lk_api_secret)document.getElementById('lk_api_secret').value=d.lk_api_secret;"
"if(d.lk_room)document.getElementById('lk_room').value=d.lk_room;"
"if(d.device_id)document.getElementById('device_id').value=d.device_id;"
"var s=document.getElementById('status');"
"s.innerHTML='<h2>Device Info</h2>'"
"+'<div class=\"status-row\"><span class=\"status-key\">MAC</span><span class=\"status-val\">'+d.mac+'</span></div>'"
"+'<div class=\"status-row\"><span class=\"status-key\">Free Heap</span><span class=\"status-val\">'+d.free_heap+'</span></div>';"
"})"
".catch(function(){});"
"</script>"
"</body>"
"</html>";
